"""Day 19: pull every script-mode training run into one table, pick a winner, promote it.

SageMaker already *is* an experiment tracker: every training job keeps its hyperparameters,
its scraped metrics, its billable seconds and its artifact path forever. This script just asks
for them and lines them up.

Run:
    py scripts/compare_runs.py                  # table only
    py scripts/compare_runs.py --mlflow         # also log each run to a local MLflow store (./mlruns)
    py scripts/compare_runs.py --promote        # copy the winner to models/candidate/

Caveat worth saying out loud: picking the winner on March and then quoting its March score
is slightly optimistic - March chose it. A clean setup holds out a third slice for the final number.
"""
import argparse
import json
from pathlib import Path

import boto3
import pandas as pd

PROFILE, REGION, BUCKET = "ds", "ca-central-1", "dave-ds-lab-ca"
PREFIX = "sk-tips-"
PRICE_PER_HOUR = 0.134          # ml.m5.large training, ca-central-1, approx
HP_KEYS = ["learning-rate", "max-iter", "max-leaf-nodes", "min-samples-leaf", "l2-regularization", "max-rows"]
CANDIDATE = "models/candidate/"


def runs(sm):
    names = []
    for page in sm.get_paginator("list_training_jobs").paginate(
        NameContains=PREFIX, StatusEquals="Completed", SortBy="CreationTime", SortOrder="Ascending"
    ):
        names += [j["TrainingJobName"] for j in page["TrainingJobSummaries"]]

    rows = []
    for name in names:
        d = sm.describe_training_job(TrainingJobName=name)
        hp = {k: json.loads(v) for k, v in d["HyperParameters"].items() if k in HP_KEYS}
        metrics = {m["MetricName"]: round(m["Value"], 4) for m in d.get("FinalMetricDataList", [])}
        billable = d.get("BillableTimeInSeconds", 0)
        rows.append({
            "job": name,
            **hp,
            "valid_mae": metrics.get("validation:mae"),
            "valid_rmse": metrics.get("validation:rmse"),
            "valid_r2": metrics.get("validation:r2"),
            "baseline_mae": metrics.get("baseline:mae"),
            "billable_s": billable,
            "cost_usd": round(billable / 3600 * PRICE_PER_HOUR, 4),
            "artifact": d["ModelArtifacts"]["S3ModelArtifacts"],
        })
    return pd.DataFrame(rows)


def markdown_table(df):
    """Plain Markdown table - avoids pulling in tabulate just for this."""
    head = "| " + " | ".join(df.columns) + " |"
    rule = "|" + "|".join("---" for _ in df.columns) + "|"
    body = ["| " + " | ".join(str(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([head, rule] + body)


def log_to_mlflow(df):
    import mlflow  # optional: py -m pip install mlflow
    mlflow.set_tracking_uri(Path("mlruns").resolve().as_uri())
    mlflow.set_experiment("tip-regressor")
    for r in df.to_dict("records"):
        with mlflow.start_run(run_name=r["job"]):
            mlflow.log_params({k: r[k] for k in HP_KEYS if k in r})
            mlflow.log_metrics({k: r[k] for k in ["valid_mae", "valid_rmse", "valid_r2", "baseline_mae", "billable_s"]
                                if r.get(k) is not None})
            mlflow.set_tag("artifact", r["artifact"])
    print("logged", len(df), "runs to ./mlruns   ->   view with:  py -m mlflow ui")


def promote(s3, best):
    src = best["artifact"].replace(f"s3://{BUCKET}/", "")
    s3.copy_object(Bucket=BUCKET, Key=CANDIDATE + "model.tar.gz", CopySource={"Bucket": BUCKET, "Key": src})
    card = {k: (v.item() if hasattr(v, "item") else v) for k, v in best.items()}
    s3.put_object(Bucket=BUCKET, Key=CANDIDATE + "candidate.json", Body=json.dumps(card, indent=2).encode())
    print(f"promoted {best['job']}  ->  s3://{BUCKET}/{CANDIDATE}model.tar.gz  (+ candidate.json)")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--mlflow", action="store_true")
    p.add_argument("--promote", action="store_true")
    args = p.parse_args()

    session = boto3.Session(profile_name=PROFILE, region_name=REGION)
    df = runs(session.client("sagemaker"))
    if df.empty:
        print("no completed", PREFIX, "jobs yet")
        return

    df = df.sort_values("valid_mae").reset_index(drop=True)
    cols = ["job"] + [k for k in HP_KEYS if k in df] + ["valid_mae", "valid_r2", "billable_s", "cost_usd"]
    with pd.option_context("display.width", 200, "display.max_columns", 20):
        print(df[cols].to_string(index=False))
    print(f"\n{len(df)} runs, total ${df['cost_usd'].sum():.3f}. "
          f"Spread in MAE best-to-worst: ${df['valid_mae'].max() - df['valid_mae'].min():.4f}")

    best = df.iloc[0]
    print(f"winner: {best['job']}  MAE ${best['valid_mae']:.4f}  (rule-of-thumb baseline ${best['baseline_mae']:.4f})")

    Path("notes").mkdir(exist_ok=True)
    Path("notes/experiments.md").write_text(
        "# Day 19 experiment runs\n\nGenerated by `scripts/compare_runs.py`. Sorted by validation MAE (March).\n\n"
        + markdown_table(df[cols]) + "\n", encoding="utf-8")
    print("wrote notes/experiments.md")

    if args.mlflow:
        log_to_mlflow(df)
    if args.promote:
        promote(session.client("s3"), best)


if __name__ == "__main__":
    main()
